[[headers]]
  for = "/unity-build/gzip/*.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/gzip"

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"