import Head from "next/head";
import MuteLottie from "./UI/MuteLottie";
import Sound from "./Sound";

export default function Layout({ children }: any) {

  return (
    <>
      <Head>
        <title>Silver Fern Farms Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fern_logo_white.png" />
      </Head>
      <main>
        <MuteLottie />
        <Sound />
        {children}
      </main>
      
    </>
  )
}