import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const documentHeight = () => {
  const doc = document.documentElement
    doc.style.setProperty('--doc-height', `${window.innerHeight}px`)
  }
  window.addEventListener("resize", documentHeight)
  documentHeight()
  return (
    <>
      <Head>
        <title>Silver Fern Farms Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fern_logo_white.png" />
      </Head>
      <main>
      </main>
    </>
  )
}
